name: Deploy PHP to cPanel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to cPanel
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.CPANEL_HOST }}
          username: ${{ secrets.CPANEL_USERNAME }}
          key: ${{ secrets.CPANEL_SSH_KEY }}
          passphrase: ${{ secrets.CPANEL_SSH_PASSPHRASE }}
          script: |
            cd /home/aslambdc/project/cPanel
            git pull origin main
